# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Optimal Segmentation
#' @param data_vec numeric data vector of response variables[1 x n]
#' @param Kmax int desired number of segments
#' @importFrom Rcpp evalCpp
#' @useDynlib ChangepointPackage
#' @returns Output list including the changepoint locations and the cluster assignment vector [1 x n]
#' @export
DynamProg_interface <- function(data_vec, Kmax) {
    .Call('_ChangepointPackage_DynamProg_interface', PACKAGE = 'ChangepointPackage', data_vec, Kmax)
}

#' Compute Square Loss
#' @param sum_vec vector of cumulatively summed input data values [1 x N]
#' @param N_vec vector from 1 to N [1 x N]
#' @useDynlib ChangepointPackage
#' @returns vector loss values [1 x N]
#' @export
#' [Rcpp::depends(RcppArmadillo)]
loss <- function(sum_vec, N_vec) {
    .Call('_ChangepointPackage_loss', PACKAGE = 'ChangepointPackage', sum_vec, N_vec)
}

